### ISSUE TITLE
Dont force this bloat on users, Mozilla. Not Pocket 2.0

### ISSUE THREAD

**Issue by du82** [Mozilla-Ocho/Memory-Cache#42]
Just more bloatware for Mozilla to shove into Firefox just like Pocket.

No one wants these random AIs, they just want to open a web browser and type chat.openai.com and talk there. We dont want a goddamn AI in every app and service we use.

End this madness please, dont force it upon me in firefox where I must use more scripts to remove the bloat.

**Comment by chrisonntag** [comment]
Hey @du82, 
I kind of share your concerns here (except for Pocket in this particular case), as I'm also a fan of the "do one thing well" unix spirit. But this project is an early research project, used to explore further ways of interacting with AI, beyond the ubiquitous chat interface these days. 

I get that not everyone may be interested in such features included in a browser, but I very much appreciate the idea and way of interacting with AI here – without the [humanization through chatting](https://informatics.tuwien.ac.at/news/2444). Kind of reminds me of the [Digital Garden](https://maggieappleton.com/garden-history).


> Q: Is this a Firefox project?
> 
> No. MemoryCache is a hackathon-style project by the Mozilla Innovation Ecosystem team, not a Firefox project.While the project uses a Firefox extension as a way of collecting information, this is a set of scripts and tools to augment privateGPT, a native AI application. It’s meant to streamline the process of saving information that you might read in the browser to store it in your own personal library of information.
https://memorycache.ai/faq.html

**Comment by du82** [comment]
> Hey @du82, I kind of share your concerns here (except for Pocket in this particular case), as I'm also a fan of the "do one thing well" unix spirit. But this project is an early research project, used to explore further ways of interacting with AI, beyond the ubiquitous chat interface these days.
> 
> I get that not everyone may be interested in such features included in a browser, but I very much appreciate the idea and way of interacting with AI here – without the [humanization through chatting](https://informatics.tuwien.ac.at/news/2444). Kind of reminds me of the [Digital Garden](https://maggieappleton.com/garden-history).
> 
> > Q: Is this a Firefox project?
> > No. MemoryCache is a hackathon-style project by the Mozilla Innovation Ecosystem team, not a Firefox project.While the project uses a Firefox extension as a way of collecting information, this is a set of scripts and tools to augment privateGPT, a native AI application. It’s meant to streamline the process of saving information that you might read in the browser to store it in your own personal library of information.
> > https://memorycache.ai/faq.html

I just fear that someday it'll become another thing we've gotta add to debloat scripts bwcause they might try to integrate AI deeply into Firefox

**Comment by misslivirose** [comment]
Hey @du82 - for some background on the project, as chrisonntag shared, this is not a project that is part of Firefox. I was interested in experimenting with ways that I can incorporate my own browsing history into a local AI that I run because despite your claim that "everyone just wants to go to chat.openai", I personally don't share that opinion and don't use OpenAI, but wanted to explore alternative RAG implementations and am using this project to share what is working for my own use case locally. 

I hear your concerns about Firefox and how AI features do or do not make it into the browser. It sounds like you have concerns about the way that intermediaries are plugging AI into software at scale, which is an opinion I personally share. I've migrated off of Dropbox and Notion because I don't need or want those capabilities built into every part of my workflow without consent. My approach to this project was specifically because of that philosophy, and wanting to share an alternative approach that makes hacking on and taking ownership of the browser experience more accessible to people.   

You will probably have better luck discussing features that are part of Firefox's actual roadmap on [https://connect.mozilla.org/](https://connect.mozilla.org/), because that's a channel monitored by the Firefox team (which I am not on).
